services:
  moodle-sync-service:
    build: .
    container_name: moodle_sync_api
    ports:
      - '8081:8081'
    environment:
      - MOODLE_API_URL=https://moodle.kpi.ua/webservice/rest/server.php
      - MOODLE_API_TOKEN=your_moodle_secret_token
      - APP_API_KEY=your_campus_integration_key
    volumes:
      - ./src/main/resources/students.txt:/src/main/resources/students.txt