spring.application.name=moodle-campus-sync
server.port=8081
moodle.api.url=${MOODLE_API_URL:http://localhost:80/webservice/rest/server.php}
moodle.api.token=${MOODLE_API_TOKEN:999f62a8ec5e1ca83b245d4206fc25d2}
campus.api.key=${APP_API_KEY:kpi_campus_secret_key_2026}