spring.application.name=moodle-campus-sync
server.port=8081
moodle.api.token=c9b2c817c0ef101680f50cb7ce45a380
moodle.api.url=http://localhost:80/webservice/rest/server.php
# moodle.api.url=http://localhost:8082/webservice/rest/server.php
# moodle.api.token=e2f99e566caa9e49e3665d3985415a76
campus.api.key=kpi_campus_secret_key_2026